// generated by stringer -type=kind; DO NOT EDIT

package main

import "fmt"

const _kind_name = "kindEolkindPtrkindIfacekindEface"

var _kind_index = [...]uint8{0, 7, 14, 23, 32}

func (i kind) String() string {
	if i < 0 || i+1 >= kind(len(_kind_index)) {
		return fmt.Sprintf("kind(%d)", i)
	}
	return _kind_name[_kind_index[i]:_kind_index[i+1]]
}
