// generated by stringer -type=tag; DO NOT EDIT

package main

import "fmt"

const _tag_name = "tagEOFtagObjecttagOtherRoottagTypetagGoroutinetagStackFrametagParamstagFinalizertagItabtagOSThreadtagMemStatstagQueuedFinalizertagDatatagBSStagDefertagPanictagMemProftagAllocSample"

var _tag_index = [...]uint8{0, 6, 15, 27, 34, 46, 59, 68, 80, 87, 98, 109, 127, 134, 140, 148, 156, 166, 180}

func (i tag) String() string {
	if i < 0 || i+1 >= tag(len(_tag_index)) {
		return fmt.Sprintf("tag(%d)", i)
	}
	return _tag_name[_tag_index[i]:_tag_index[i+1]]
}
